### ISSUE TITLE
Could you please explain the behavior?

### ISSUE THREAD

**Issue by espdev** [mjpieters/aiolimiter#200]
Hello!

I try to use aiolimiter library, but I do not quite understand how it works.

I wrote a simple example:
```python
import asyncio
import time

from aiolimiter import AsyncLimiter

async def worker(e, limiter, i):
    await e.wait()
    st = time.time()
    async with limiter:
        print(f'{i:2d} {time.time() - st:6.2f} s')

async def main():
    tasks = []
    limiter = AsyncLimiter(10, 60.0)
    e = asyncio.Event()

    for i in range(20):
        tasks.append(asyncio.create_task(worker(e, limiter, i)))

    e.set()  # start all
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    asyncio.run(main())
```

And I get the following results:
```
 0   0.00 s
 1   0.00 s
 2   0.00 s
 3   0.00 s
 4   0.00 s
 5   0.00 s
 6   0.00 s
 7   0.00 s
 8   0.00 s
 9   0.00 s
10   6.01 s
12  12.02 s
19  18.02 s
13  24.04 s
15  30.05 s
17  36.06 s
16  42.07 s
18  48.07 s
11  54.09 s
14  60.09 s
```

I figured I should get 2 minutes of doing 20 asynchronous tasks at 10 per minute. However I get 10 tasks done instantly and another 10 tasks done in the remaining time (~60 seconds). It's not what I expected. What am I doing or understanding wrong?

Thank you.

**Comment by mjpieters** [comment]
This is [covered in the *Bursting* section of the documentation](https://aiolimiter.readthedocs.io/en/latest/#bursting).
