### ISSUE TITLE
CHANGELOG.md installed into top-level site-packages directory

### ISSUE THREAD

**Issue by vimproved** [mjpieters/aiolimiter#206]
Currently, the pyproject.toml file is causing poetry to install CHANGELOG.md top-level into the site-packages directory when built (e.g. `/usr/lib/python3.11/site-packages/CHANGELOG.md`). See https://projects.gentoo.org/python/guide/qawarn.html#documentation-files-installed-by-poetry for more info. The fix is as follows:

In pyproject.toml, replace `include = ["CHANGELOG.md"]` with
```python
include = [
    { path = "CHANGELOG.md", format = "sdist" },
]

**Comment by mjpieters** [comment]
Thanks! This was fixed (somewhat inadvertently) in b3c6602e32bd78710812582d06b2dec2232f5d9b.
