### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by bryzgaloff** [mjpieters/aiolimiter#60]
Traceback when running on Python 3.10:

```
  File "…/python3.10/site-packages/aiolimiter/leakybucket.py", line 110, in __aenter__
    await self.acquire()
  File "…/python3.10/site-packages/aiolimiter/leakybucket.py", line 97, in acquire
    await asyncio.wait_for(
TypeError: wait_for() got an unexpected keyword argument 'loop'
```

Reason:
> Deprecated since version 3.8, removed in version 3.10: The loop parameter. This function has been implicitly getting the current running loop since 3.7. See What’s New in 3.10’s Removed section for more information.

From `wait_for` documentation: https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for

PS thank you very much for the project, very useful! Also following good asyncio practices, very nice! I suggest you applying to join aio-libs organization on GitHub.

**Comment by mjpieters** [comment]
Ah yes, I've been punting on that one. Want to make a PR? :-)

**Comment by mjpieters** [comment]
Actually, that issue was fixed [in September 2020](https://github.com/mjpieters/aiolimiter/pull/46), but I never cut a release. So this one is entirely on me.

**Comment by mjpieters** [comment]
I've pushed v1.0.0, all being well it should be [pushed to PyPI soon](https://dev.azure.com/mjpieters/aiolimiter/_build/results?buildId=291&view=results).
